import '@/src/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link"
import { Main } from "@/src/app/copornents/Main";
import { Linkarea } from '@/src/app/copornents/Linkarea';
import { Logo } from '@/src/app/copornents/Logo ';
import { Segment } from '@/src/app/copornents/Segment';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen">
          <div className="flex container text-white text-2xl p-4 justify-between font-mono font-bold border-b-2 border-gray-500 border-dashed duration-300" >
            <h2 className="transition ease-in-out delay-150 hover:translate-x-1 ">Header</h2>
            
            <Segment />
          </div>
          <Main />
          {children}
          <Logo />
          <Linkarea />
        </main>
        
        
      </body>
    </html>
  )
}
