import '@/src/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex  container text-white text-2xl p-4 justify-between font-mono font-bold border-b-2 border-gray-500 border-dashed duration-300" >
          <h2 className="transition ease-in-out delay-150 hover:translate-x-1 ">Header</h2>
          <div className="opacity-75 space-x-10 " >
            <Link className="transition ease-in-out delay-150 hover:text-black" href="/">
              app
            </Link>
            <Link className="transition ease-in-out delay-150 hover:text-black" href="/about">
              about
            </Link>
          </div>
          
        </div>
        
        {children}
      </body>
    </html>
  )
}
